
rarity_map = {
    1: "💫 Rare",
    2: "🌿 Medium",
    3: "🦄 Legendary",
    4: "💮 Special Edition",
    5: "🔮 Limited Edition",
    6: "🎉 Festival",
    7: "🍂 Seasonal",
    8: "🎐 Celestial", 
    9: "❄️ Winter",
    10: "💝 Valentine",
    11: "🔞 Erotic",
    12: "🪽 AMV",
    13: "✨ Aristocratic",
    14: "🕌 Fast edition",
    15: "🎬 Hollywood",
    16: "🎃 Halloween",
}

rarity_map2 = {
     "💫 Rare": "💫",
     "🌿 Medium": "🌿",
     "🦄 Legendary": "🦄",
     "💮 Special Edition": "💮",
     "🔮 Limited Edition": "🔮",
     "🎉 Festival": "🎉",
     "🍂 Seasonal": "🍂",
     "🎐 Celestial": "🎐",
     "❄️ Winter": "❄️",
     "💝 Valentine": "💝",
     "🔞 Erotic": "🔞",
     "🪽 AMV": "🪽",
     "✨ Aristocratic": "✨",
     "🕌 Fast edition": "🕌",
     "🎬 Hollywood": "🎬",
     "🎃 Halloween": "🎃",
}


RARITY_MAPPING = {
    '💫 Rare':  '💫',
    '🌿 Medium': '🌿',
    '🦄 Legendary': '🦄',
    '💮 Special Edition': '💮',
    '🔮 Limited Edition': '🔮',
    '🎉 Festival': '🎉', 
    '🍂 Seasonal': '🍂',
    '🎐 Celestial': '🎐', 
    '❄️ Winter': '❄️',
    '💝 Valentine': '💝',
    '🔞 Erotic': '🔞',
    '🪽 AMV': '🪽',
    '✨ Aristocratic': '✨',
    '🕌 Fast edition': '🕌',
    '🎬 Hollywood': '🎬',
    '🎃 Halloween': '🎃',
}

RARITY_R = [
    ("💫 Rare", 800),
    ("🌿 Medium", 6000),
    ("🦄 Legendary", 4000),
    ("💮 Special Edition", 1000),
    ("🔮 Limited Edition", 9000),
    ("🎉 Festival", 10000),
    ("🍂 Seasonal", 40000),
    ("🎐 Celestial", 40000),
    ("❄️ Winter", 25000),
    ("💝 Valentine", 12000),
    ("🔞 Erotic", 20000),
    ("🪽 AMV", 50000),
    ("✨ Aristocratic", 60000),
    ("🕌 Fast edition", 40000),
    ("🎬 Hollywood", 40000),
    ("🎃 Halloween", 40000),
]

RARITY_2 = [
    ("⚪️ Common", 800),
    ("🟣 Rare", 6000),
    ("🟡 Legendary", 4000),
    ("🟢 Medium", 1000),
    ("💮 Special Edition", 9000),
    ("🔮 Limited Edition", 10000),
    ("🎐 Celestial", 40000),
    ("💖 Valentine", 20000),
    ("🎃 Halloween", 25000),
    ("❄️ Winter", 12000),
    ("💸 Expensive", 19000),
    ("💌 AMV", 50000),
    ("🏖 Summer", 23000),
    ("🧬 X-Verse", 36500),
    ("✨ Neon", 20000),
    ("⚜ Royal", 35000)
]

bounty_values = {
            '💫 Rare': 100,
            '🌿 Medium': 150,
            '🦄 Legendary': 200,
            '💮 Special Edition': 300,
            '🔮 Limited Edition': 400,
            '🎉 Festival': 500,
            '🍂 Seasonal': 600,
            '🎐 Celestial': 700,
            '❄️ Winter': 800,
            '💝 Valentine': 1000,
            '🔞 Erotic': 650,
            '🪽 AMV': 500,
            '✨ Aristocratic': 450,
            '🕌 Fast edition': 260,
            '🎬 Hollywood': 400,
            '🎃 Halloween': 500,
          
            
}
